server:
  port: 9527

# 部署到服务器的环境
echo:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host:
    port: 3306
    database: virtual_interview_db
    username: echo
    password: ***REMOVED***
  redis:
    host:
    port: 6379
    database: 3 #9是py的
    password:
  oss:
    endpoint:
    access-key-id:
    access-key-secret:
    bucket-name: echo-interview





